/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        // restaurant class instance
        Restaurant restaurant=new Restaurant("ward",5,"$$$$");
        System.out.println(restaurant);
        //review instance test
        Review review=new Review("this is text review","yousef",4);
        System.out.println(review);
        System.out.println("\n");
Review restaurantReview=new Review("wonderful place","Jamal",4);
        restaurant.addReview(restaurantReview);
        System.out.println(restaurantReview);

    }
}
