/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.*;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";

    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
//        gatesReader();
        gatesReader2();
    }

    public static void gatesReader() {

        File file = new File("app/src/main/resources/gates.js");
        System.out.println(file);

        try (Scanner scanner = new Scanner(file)) {
            while (scanner.hasNextLine()) {

                if (scanner.nextLine().isEmpty()) {
                    continue;

                }
                if (scanner.nextLine().endsWith("{")) {
                    continue;

                }
                if (scanner.nextLine().endsWith("}")) {
                    continue;

                }
                if (scanner.nextLine().contains("if") || scanner.nextLine().contains("else")) {
                    continue;

                }
                if (!scanner.nextLine().endsWith(";")) {

                    System.err.println("Line: Missing semicolon.");

                }

                scanner.nextLine();

            }

        } catch (FileNotFoundException fileNotFoundException) {
            System.err.println(fileNotFoundException.getMessage());
        }
    }

    public static void gatesReader2() throws IOException {
        FileReader file = new FileReader("app/src/main/resources/gates.js");
        System.out.println(file);
        BufferedReader bufferedReader = new BufferedReader(file);

int counter=0;
        String line;
        while ((line = bufferedReader.readLine()) != null) {
            System.out.println(line);


            if (bufferedReader.readLine().isEmpty()) {
                counter++;
                continue;


            }
            if (bufferedReader.readLine().endsWith("{")) {
                counter++;
                continue;

            }
            if (bufferedReader.readLine().endsWith("}")) {
              counter++;
                continue;

            }
            if (bufferedReader.readLine().contains("if") || bufferedReader.readLine().contains("else")) {
              counter++;
                continue;

            }
            if (bufferedReader.readLine().contains("return")&&!bufferedReader.readLine().endsWith(";")) {

                System.err.println("Line"+counter+": Missing semicolon.");


            }
            bufferedReader.readLine();


            counter++;


        }
    }
}










